### ISSUE TITLE
Unhandled Rejection at: Promise Promise at DNS._ontimeout

### ISSUE THREAD

**Issue by romansemko** [SemkoDev/nelson.mon#1]
shortly after starting nelson it logs the following error - but it continues working and everything else seems to be fine:

[4:21] 
Unhandled Rejection at: Promise Promise {
 <rejected> Error: Query timed out
   at DNS._ontimeout (/usr/lib/node_modules/nelson.cli/node_modules/dns-socket/index.js:98:18)
   at Timeout.ontimeout (/usr/lib/node_modules/nelson.cli/node_modules/dns-socket/index.js:52:10)
   at ontimeout (timers.js:386:14)
   at tryOnTimeout (timers.js:250:5)
   at Timer.listOnTimeout (timers.js:214:5) } reason: Error: Query timed out
   at DNS._ontimeout (/usr/lib/node_modules/nelson.cli/node_modules/dns-socket/index.js:98:18)
   at Timeout.ontimeout (/usr/lib/node_modules/nelson.cli/node_modules/dns-socket/index.js:52:10)
   at ontimeout (timers.js:386:14)
   at tryOnTimeout (timers.js:250:5)
   at Timer.listOnTimeout (timers.js:214:5

**Comment by romansemko** [comment]
DNS lookup for own IP address fails. It is not critical, but annoying.

**Comment by romansemko** [comment]
Fixed already
